import type { CorrectOption } from "../src/generated/prisma/enums";

export interface QuestionSeed {
  questionText: string;
  imageUrl?: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: CorrectOption;
  explanation: string;
  category: string;
  difficulty: number;
}

export const questions: QuestionSeed[] = [
  {
    questionText: "Wat betekent iASV in de context van Hamilton-beademing?",
    imageUrl: "/images/quiz/iasv-overview.svg",
    optionA: "Intelligent Adaptive Support Ventilation",
    optionB: "Intermittent Airway Support Ventilation",
    optionC: "Invasive Automatic Spontaneous Ventilation",
    optionD: "Integrated Alarm Safety Ventilation",
    correctOption: "A",
    explanation:
      "iASV staat voor Intelligent Adaptive Support Ventilation (Adaptive Support Ventilation). Het is een closed-loop ventilatiemodus die ademfrequentie, tidal volume en inspiratietijd automatisch aanpast.",
    category: "basis",
    difficulty: 1,
  },
  {
    questionText: "Op welke ventilatoren is ASV beschikbaar?",
    imageUrl: "/images/quiz/hamilton-ventilator.svg",
    optionA: "Alleen op Hamilton Medical ventilatoren",
    optionB: "Op alle ICU-ventilatoren",
    optionC: "Alleen op transportventilatoren",
    optionD: "Alleen op neonatale ventilatoren",
    correctOption: "A",
    explanation:
      "ASV is exclusief beschikbaar op Hamilton Medical ventilatoren (C1, C3, C6, T1, MR1). Andere merken bieden geen ASV-modus.",
    category: "basis",
    difficulty: 1,
  },
  {
    questionText: "Hoeveel hoofdparameters stelt de gebruiker typisch in bij ASV?",
    imageUrl: "/images/quiz/settings-panel.svg",
    optionA: "Drie: % MinVol, PEEP en Pasv limit",
    optionB: "Vijf: TV, RR, PEEP, FiO2 en I:E",
    optionC: "Twee: alleen PEEP en FiO2",
    optionD: "Zeven: alle conventionele parameters",
    correctOption: "A",
    explanation:
      "ASV vereenvoudigt ventilatie: de gebruiker stelt vooral % MinVol (doel-minuutvolume), PEEP en Pasv limit in. TV en RR worden automatisch bepaald.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Hoe wordt het doel-minuutvolume bij volwassenen berekend in ASV?",
    imageUrl: "/images/quiz/minvol-calc.svg",
    optionA: "0,1 L/kg ideaal lichaamsgewicht (IBW) × % MinVol",
    optionB: "0,5 L/kg actueel lichaamsgewicht × % MinVol",
    optionC: "6 ml/kg actueel gewicht × ademfrequentie",
    optionD: "Vast 8 L/min ongeacht gewicht",
    correctOption: "A",
    explanation:
      "Bij volwassenen: minuutvolume = 0,1 L/kg IBW. Bij 100% MinVol en IBW 70 kg is dat 7 L/min. Bij 50% MinVol is het 3,5 L/min.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Een volwassen patient heeft IBW 80 kg. Wat is het minuutvolume bij 100% MinVol?",
    optionA: "8 L/min",
    optionB: "4 L/min",
    optionC: "16 L/min",
    optionD: "0,8 L/min",
    correctOption: "A",
    explanation: "80 kg × 0,1 L/kg = 8 L/min bij 100% MinVol.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke ventilatiepatronen kan ASV automatisch afwisselen?",
    imageUrl: "/images/quiz/ventilation-modes.svg",
    optionA: "PCV, PSV en SIMV-P",
    optionB: "Alleen volume-gestuurd",
    optionC: "Alleen HFJV",
    optionD: "Alleen CPAP zonder druk",
    correctOption: "A",
    explanation:
      "ASV wisselt breath-by-breath tussen pressure-controlled ventilation (PCV), pressure support (PSV) en SIMV-P, afhankelijk van patientinspanning en longmechanica.",
    category: "basis",
    difficulty: 2,
  },
  {
    questionText: "Wat is een belangrijk voordeel van closed-loop ventilatie zoals ASV?",
    optionA: "Continue automatische aanpassing aan patient en longmechanica",
    optionB: "Geen monitoring meer nodig",
    optionC: "Vaste TV en RR ongeacht patient",
    optionD: "Werkt zonder flowsensor",
    correctOption: "A",
    explanation:
      "ASV past ademhalingspatroon continu aan op basis van gemeten longmechanica en patientinspanning, wat de klinische workload kan verlagen.",
    category: "basis",
    difficulty: 1,
  },
  {
    questionText: "Waarvoor dient de Pasv limit instelling?",
    imageUrl: "/images/quiz/pasv-limit.svg",
    optionA: "Maximale inspiriumdruk die ASV mag gebruiken",
    optionB: "Minimale PEEP waarde",
    optionC: "Maximale FiO2",
    optionD: "Expiratoire trigger gevoeligheid",
    correctOption: "A",
    explanation:
      "Pasv limit (passive limit) beperkt de maximale inspiriumdruk. Standaard vaak 30 cmH2O bij normale patienten, lager bij ARDS.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat is een gangbare startinstelling voor % MinVol bij een normale volwassen patient?",
    optionA: "100%",
    optionB: "30%",
    optionC: "200%",
    optionD: "0%",
    correctOption: "A",
    explanation:
      "100% MinVol is een veelgebruikte startwaarde. Bij ARDS wordt soms 120% gekozen; sommigen starten op 110% vanwege dead space.",
    category: "instellingen",
    difficulty: 1,
  },
  {
    questionText: "Waarom kan ASV NIET geschikt zijn bij een groot lek in het ademhalingscircuit?",
    imageUrl: "/images/quiz/leak-warning.svg",
    optionA: "De flowsensor meet onbetrouwbaar volume bij lekkage",
    optionB: "ASV werkt alleen bij hoge PEEP",
    optionC: "Hamilton ventilatoren ondersteunen geen lekkage",
    optionD: "ASV verhoogt automatisch FiO2 bij lek",
    correctOption: "A",
    explanation:
      "Bij lekkages (cuff leak, bronchopleurale fistel, open pneumothorax) is volume- en flowmeting onbetrouwbaar. ASV is dan gecontra-indiceerd.",
    category: "contra-indicaties",
    difficulty: 2,
  },
  {
    questionText: "Welke situatie is een contra-indicatie voor ASV?",
    optionA: "Ernstige metabole acidose met zeer hoge ventilatiebehoefte",
    optionB: "Postoperatieve patient zonder complicaties",
    optionC: "Normale spontane ademhaling",
    optionD: "Milde COPD",
    correctOption: "A",
    explanation:
      "Bij ernstige metabole acidose wil je soms expliciet hoge RR/TV instellen. ASV stuurt automatisch en laat niet altijd toe wat klinisch gewenst is.",
    category: "contra-indicaties",
    difficulty: 3,
  },
  {
    questionText: "Waarom is ASV problematisch bij abnormale ademhalingspatronen?",
    optionA: "Het algoritme kan niet goed interpreteren wat gewenst ademhalingsgedrag is",
    optionB: "ASV schakelt automatisch uit bij Cheyne-Stokes",
    optionC: "De ventilator geeft dan alleen CPAP",
    optionD: "FiO2 kan niet worden aangepast",
    correctOption: "A",
    explanation:
      "Bij abnormale patronen (Cheyne-Stokes, frequent apnea) interpreteert ASV patientinspanning en mechanica verkeerd.",
    category: "contra-indicaties",
    difficulty: 2,
  },
  {
    questionText: "Wat meet de proximale flowsensor bij Hamilton ventilatoren?",
    imageUrl: "/images/quiz/proximal-sensor.svg",
    optionA: "Flow en volume dicht bij de patient (Y-stuk)",
    optionB: "Alleen druk in het expiratieventiel",
    optionC: "Alleen bloeddruk",
    optionD: "Alleen FiO2 aan de machinezijde",
    correctOption: "A",
    explanation:
      "De proximale flowsensor meet flow en volume aan de patientzijde, wat nauwkeuriger is dan alleen ventilator-side meting, vooral bij lekkage.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is RCexp in de context van ASV 1.1?",
    optionA: "Expiratoire tijdconstante van de longen",
    optionB: "Residuale CO2 in expirat",
    optionC: "Respiratoire compliance van de thoraxwand",
    optionD: "Ratio compressie/expansie",
    correctOption: "A",
    explanation:
      "ASV 1.1 meet breath-by-breath RCexp (expiratoire tijdconstante) om longmechanica te beoordelen en optimale RR/TV te kiezen.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Welk wiskundig model ligt ten grondslag aan ASV?",
    imageUrl: "/images/quiz/otis-equation.svg",
    optionA: "Aangepaste Otis-vergelijking",
    optionB: "Bernoulli-vergelijking",
    optionC: "Starling-vergelijking",
    optionD: "Boyle's wet alleen",
    correctOption: "A",
    explanation:
      "ASV gebruikt een aangepaste Otis-vergelijking om het ademhalingspatroon te vinden met minste ademhalingswerk bij het gekozen minuutvolume.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Wat is het doel van lung-protective strategie in ASV?",
    imageUrl: "/images/quiz/lung-protective.svg",
    optionA: "Barotrauma, volutrauma en AutoPEEP voorkomen",
    optionB: "Maximaal minuutvolume leveren",
    optionC: "Altijd hoge plateau druk",
    optionD: "Spontane ademhaling volledig onderdrukken",
    correctOption: "A",
    explanation:
      "ASV streeft naar lung-protective ventilatie: voorkomen van te grote breaths, te hoge drukken, apneu, tachypneu en dead-space ventilatie.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is AutoPEEP?",
    optionA: "Positieve expiratoire druk door incomplete expiratie",
    optionB: "Automatisch ingestelde PEEP door de verpleegkundige",
    optionC: "PEEP gemeten in het bloed",
    optionD: "FiO2 die automatisch stijgt",
    correctOption: "A",
    explanation:
      "AutoPEEP (intrinsic PEEP) ontstaat wanneer expiratie niet afloopt voor de volgende inspiratie. ASV probeert dit te minimaliseren.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wanneer in het ventilatieproces kan ASV worden gebruikt?",
    imageUrl: "/images/quiz/intubation-extubation.svg",
    optionA: "Van intubatie tot extubatie",
    optionB: "Alleen tijdens weaning",
    optionC: "Alleen eerste 24 uur",
    optionD: "Alleen bij NIV",
    correctOption: "A",
    explanation:
      "ASV kan worden gebruikt gedurende het hele beademingsproces: initiatie, onderhoud en weaning, zowel bij passieve als actieve patienten.",
    category: "weaning",
    difficulty: 1,
  },
  {
    questionText: "Hoe kan ASV het weaningproces ondersteunen?",
    optionA: "Door % MinVol geleidelijk te verlagen naarmate de patient meer spontaan ademt",
    optionB: "Door automatisch te extuberen",
    optionC: "Door PEEP altijd op 0 te zetten",
    optionD: "Door sedatie automatisch te verhogen",
    correctOption: "A",
    explanation:
      "Bij afnemende beademingsbehoefte kan % MinVol omlaag. ASV past RR/TV aan terwijl de patient meer spontane ademhaling levert.",
    category: "weaning",
    difficulty: 2,
  },
  {
    questionText: "Wat gebeurt er als een patient op ASV meer spontaan gaat ademen?",
    optionA: "ASV geeft meer drukondersteuning (PSV-achtig) en past RR aan",
    optionB: "ASV stopt volledig met beademen",
    optionC: "ASV verhoogt altijd PEEP met 5 cmH2O",
    optionD: "ASV schakelt over naar HFNC",
    correctOption: "A",
    explanation:
      "Bij spontane inspanning schakelt ASV naar meer ondersteunende modi (PSV) en past frequentie en volume aan binnen het doel-minuutvolume.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is IntelliVent-ASV?",
    imageUrl: "/images/quiz/intellivent.svg",
    optionA: "Uitbreiding van ASV die ook FiO2 en PEEP automatisch stuurt",
    optionB: "Een apart merk ventilator",
    optionC: "Alleen een alarmfunctie",
    optionD: "Een mode voor thuisbeademing",
    correctOption: "A",
    explanation:
      "IntelliVent-ASV breidt ASV uit met automatische sturing van oxygenatie (FiO2) en PEEP op basis van SpO2/PaO2 en andere parameters.",
    category: "basis",
    difficulty: 2,
  },
  {
    questionText: "Welke patientpopulatie kan ASV ondersteunen?",
    optionA: "Volwassenen en pediatrische patienten",
    optionB: "Alleen neonaten onder 3 kg",
    optionC: "Alleen traumapatiente",
    optionD: "Alleen COPD-patienten",
    correctOption: "A",
    explanation:
      "ASV kan bij volwassenen en pediatrische patienten worden gebruikt. Pediatrisch minuutvolume wordt anders berekend (0,3 L/kg bij 3 kg tot 0,1 L/kg bij 30 kg).",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Hoe wordt minuutvolume bij een kind van 10 kg (pediatrisch) benaderd in ASV?",
    optionA: "Via een pediatrische schaal tussen 0,3 en 0,1 L/kg IBW",
    optionB: "Altijd 6 L/min vast",
    optionC: "Via actueel gewicht × 0,5 L/kg",
    optionD: "Niet mogelijk in ASV",
    correctOption: "A",
    explanation:
      "Pediatrisch: minuutvolume loopt van 0,3 L/kg bij IBW 3 kg naar 0,1 L/kg bij IBW 30 kg. Bij 10 kg zit je tussen die waarden in.",
    category: "instellingen",
    difficulty: 3,
  },
  {
    questionText: "Wat is volutrauma?",
    optionA: "Longschade door te grote tidal volumes",
    optionB: "Schade door te lage FiO2",
    optionC: "Infectie door beademing",
    optionD: "Droge slijmvliezen door HFNC",
    correctOption: "A",
    explanation:
      "Volutrauma is longschade door overdistensie (te grote TV). ASV probeert dit te voorkomen via lung-protective limieten.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Wat is barotrauma?",
    optionA: "Longschade door te hoge drukken in het ademhalingsstelsel",
    optionB: "Schade door zuurstoftoxiciteit",
    optionC: "Spiervermoeidheid door hoesten",
    optionD: "Allergische reactie op filters",
    correctOption: "A",
    explanation:
      "Barotrauma ontstaat door excessieve druk (bijv. pneumothorax). Pasv limit helpt dit te beperken.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Waarom kan ASV mechanical power verlagen t.o.v. conventionele modi?",
    imageUrl: "/images/quiz/mechanical-power.svg",
    optionA: "Het kiest lagere optimale RR en drukken via het algoritme",
    optionB: "Het gebruikt geen drukventilatie",
    optionC: "Het schakelt ventilatie elke 4 uur uit",
    optionD: "Het verhoogt altijd TV",
    correctOption: "A",
    explanation:
      "ASV 1.1 selecteert frequentie en volume met lagere ademhalingskracht en mechanical power, wat gunstig kan zijn voor longbescherming.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Wat is flow trigger?",
    optionA: "Start inspiratie bij een bepaalde flowafwijking t.o.v. baseline",
    optionB: "Automatische PEEP-verhoging",
    optionC: "Expiratoire pauze instelling",
    optionD: "Maximale inspiratieflow",
    correctOption: "A",
    explanation:
      "Flow trigger bepaalt wanneer een inspiratoire effort wordt herkend. Te gevoelig kan auto-triggering geven; te ongevoelig vertraagt trigger.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat doet P-ramp (pressure ramp)?",
    optionA: "Bepaalt hoe snel inspiriumdruk wordt opgebouwd",
    optionB: "Verhoogt PEEP bij desaturatie",
    optionC: "Meet plateau druk",
    optionD: "Stelt ETS in",
    correctOption: "A",
    explanation:
      "P-ramp regelt de snelheid van drukopbouw. Langere ramp kan comfort verbeteren; kortere ramp kan sneller volume leveren.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat is ETS (Expiratory Trigger Sensitivity)?",
    imageUrl: "/images/quiz/breath-cycle.svg",
    optionA: "Gevoeligheid waarmee inspiratie wordt beeindigd",
    optionB: "Expiratoire PEEP waarde",
    optionC: "Trigger voor hartfrequentie",
    optionD: "ETS is hetzelfde als I:E ratio",
    correctOption: "A",
    explanation:
      "ETS bepaalt wanneer de ventilator van inspiratie naar expiratie schakelt bij druk- of volume-gestuurde breaths.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke instelling beinvloedt vooral oxygenatie in standaard ASV (niet IntelliVent)?",
    optionA: "PEEP en FiO2 (handmatig door gebruiker)",
    optionB: "Alleen % MinVol",
    optionC: "Alleen Pasv limit",
    optionD: "Alleen flow trigger",
    correctOption: "A",
    explanation:
      "In standaard ASV stuurt de gebruiker oxygenatie via PEEP en FiO2. % MinVol regelt vooral ventilatie (CO2). IntelliVent automatiseert ook oxygenatie.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke instelling regelt vooral alveolaire ventilatie (CO2) in ASV?",
    optionA: "% MinVol",
    optionB: "Alleen PEEP",
    optionC: "Alleen FiO2",
    optionD: "Alleen humidifier temperatuur",
    correctOption: "A",
    explanation:
      "% MinVol bepaalt het doel-minuutvolume en daarmee in belangrijke mate alveolaire ventilatie en CO2-eliminatie.",
    category: "instellingen",
    difficulty: 1,
  },
  {
    questionText: "Patient met ARDS: welke % MinVol startwaarde is vaak geschikter dan 100%?",
    optionA: "120%",
    optionB: "50%",
    optionC: "10%",
    optionD: "300%",
    correctOption: "A",
    explanation:
      "Bij ARDS wordt vaak 120% MinVol als startpunt genoemd vanwege verhoogd dead space en verhoogde ventilatiebehoefte.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Waarom is ASV soms minder geschikt bij restrictieve longziekte met zeer lage TV-behoefte?",
    optionA: "Je kunt TV en RR niet direct handmatig forceren",
    optionB: "Hamilton ventilatoren ondersteunen restrictieve ziekte niet",
    optionC: "ASV geeft altijd TV van 10 ml/kg",
    optionD: "PEEP werkt niet bij restrictieve ziekte",
    correctOption: "A",
    explanation:
      "Bij restrictieve longziekte wil je soms expliciet lage TV. ASV stuurt automatisch en laat beperkte directe TV/RR-controle toe.",
    category: "contra-indicaties",
    difficulty: 3,
  },
  {
    questionText: "Wat is dead-space ventilatie?",
    optionA: "Ventilatie van luchtwegen zonder gasuitwisseling in alveoli",
    optionB: "Ventilatie met 0 PEEP",
    optionC: "Apneu per minuut",
    optionD: "Ventilatie zonder humidificatie",
    correctOption: "A",
    explanation:
      "Dead-space ventilatie levert volume aan niet-gasuitwisselende delen. ASV probeert inefficinte hoge frequenties met kleine TV te vermijden.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Welke sensor is essentieel voor accurate ASV-werking?",
    imageUrl: "/images/quiz/proximal-sensor.svg",
    optionA: "Proximale flowsensor",
    optionB: "Transcutane CO2 sensor alleen",
    optionC: "EKG elektrode",
    optionD: "Temperatuursensor buiten circuit",
    correctOption: "A",
    explanation:
      "ASV vertrouwt op nauwkeurige flow/volumemeting via de proximale sensor voor closed-loop sturing.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is het verschil tussen ASV 1.0 en ASV 1.1?",
    optionA: "ASV 1.1 gebruikt RCexp meting en optimaliseert mechanical power beter",
    optionB: "ASV 1.0 werkt alleen bij kinderen",
    optionC: "ASV 1.1 heeft geen proximale sensor nodig",
    optionD: "Er is geen verschil",
    correctOption: "A",
    explanation:
      "ASV 1.1 meet RCexp breath-by-breath en kiest frequentie/volume met lagere mechanical power. Dit is standaard op moderne Hamilton ventilatoren.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Welke parameter mag je NIET direct instellen in ASV?",
    optionA: "Respiratory rate (RR) als vaste waarde",
    optionB: "PEEP",
    optionC: "FiO2",
    optionD: "% MinVol",
    correctOption: "A",
    explanation:
      "In ASV stel je geen vaste RR of TV in; die worden automatisch bepaald. PEEP, FiO2 en % MinVol wel.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Patient met bronchopleurale fistel (BPF): waarom ASV vermijden?",
    imageUrl: "/images/quiz/leak-warning.svg",
    optionA: "Groot lek maakt volumemeting en closed-loop sturing onbetrouwbaar",
    optionB: "BPF vereist altijd NIV",
    optionC: "ASV verhoogt fistel automatisch",
    optionD: "Hamilton ventilatoren detecteren BPF niet",
    correctOption: "A",
    explanation:
      "BPF veroorzaakt groot lek. ASV kan volume en patientinspanning niet betrouwbaar meten, waardoor onveilige sturing mogelijk is.",
    category: "contra-indicaties",
    difficulty: 3,
  },
  {
    questionText: "Wat is SIMV-P in de context van ASV?",
    optionA: "Synchronized intermittent mandatory pressure breaths",
    optionB: "Simple manual ventilation protocol",
    optionC: "Spontaneous mode without monitoring",
    optionD: "Safety mode for power failure",
    correctOption: "A",
    explanation:
      "SIMV-P combineert mandatory pressure breaths met ruimte voor spontane ademhaling. ASV kan dit patroon automatisch inzetten.",
    category: "basis",
    difficulty: 2,
  },
  {
    questionText: "Waarom is IBW (ideaal lichaamsgewicht) belangrijk voor ASV?",
    imageUrl: "/images/quiz/minvol-calc.svg",
    optionA: "Minuutvolume wordt op IBW gebaseerd, niet actueel gewicht",
    optionB: "IBW bepaalt alleen FiO2",
    optionC: "IBW is alleen voor pediatrie",
    optionD: "IBW wordt niet gebruikt in ASV",
    correctOption: "A",
    explanation:
      "ASV berekent doel-minuutvolume op basis van IBW. Bij obesitas voorkomt dit overventilatie op basis van actueel gewicht.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke complicatie kan optreden bij te hoge Pasv limit?",
    optionA: "Barotrauma door te hoge drukken",
    optionB: "Te lage PEEP",
    optionC: "Apneu door te lage TV",
    optionD: "Geen enkele",
    correctOption: "A",
    explanation:
      "Een te hoge Pasv limit staat hogere inspiriumdrukken toe, wat barotrauma kan bevorderen. Stel conservatief in bij ARDS.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat doet ASV bij apneu van de patient?",
    optionA: "Levert mandatory breaths om minuutvolume te halen",
    optionB: "Schakelt ventilator uit",
    optionC: "Verlaagt PEEP naar 0",
    optionD: "Wacht 10 minuten",
    correctOption: "A",
    explanation:
      "Bij apneu levert ASV mandatory breaths (PCV) om het ingestelde minuutvolume te behalen.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Welke rol speelt PEEP in ASV?",
    imageUrl: "/images/quiz/peep-diagram.svg",
    optionA: "Recruitment en oxygenatie ondersteunen",
    optionB: "Direct CO2 verwijderen",
    optionC: "RR automatisch verdubbelen",
    optionD: "ETS vervangen",
    correctOption: "A",
    explanation:
      "PEEP ondersteunt alveolaire recruitment en oxygenatie. In standaard ASV stel je PEEP handmatig in (IntelliVent kan automatisch).",
    category: "instellingen",
    difficulty: 1,
  },
  {
    questionText: "Waarom monitort de verpleegkundige/arts ASV-patienten nog steeds?",
    optionA: "ASV vereist klinische beoordeling en alarms opvolging",
    optionB: "ASV werkt volledig zonder supervisie",
    optionC: "Alleen voor administratie",
    optionD: "Monitoring is verboden bij ASV",
    correctOption: "A",
    explanation:
      "ASV automatiseert veel, maar vereist nog steeds monitoring van saturatie, CO2, drukken, patientcomfort en contra-indicaties.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Welke start-PEEP wordt vaak genoemd als richtlijn bij ASV?",
    optionA: "5 cmH2O of volgens ICU-protocol",
    optionB: "0 cmH2O altijd",
    optionC: "20 cmH2O standaard",
    optionD: "PEEP is niet instelbaar",
    correctOption: "A",
    explanation:
      "5 cmH2O of het lokale ICU-protocol is een veelgebruikte PEEP-startwaarde, aangepast aan patient en pathologie.",
    category: "instellingen",
    difficulty: 1,
  },
  {
    questionText: "Open pneumothorax: waarom is ASV gecontra-indiceerd?",
    imageUrl: "/images/quiz/leak-warning.svg",
    optionA: "Massief lek maakt ventilatiesturing onbetrouwbaar",
    optionB: "Pneumothorax vereist altijd CPAP",
    optionC: "ASV verhoogt automatisch thoraxdrain",
    optionD: "FiO2 kan niet worden ingesteld",
    correctOption: "A",
    explanation:
      "Bij open pneumothorax is er een groot lek. ASV kan volume niet betrouwbaar meten; kies een andere mode tot het lek is opgelost.",
    category: "contra-indicaties",
    difficulty: 2,
  },
  {
    questionText: "Hoe vaardig moet ICU-personeel zijn met ASV?",
    optionA: "Getraind in ASV-principes, instellingen en beperkingen",
    optionB: "Geen training nodig",
    optionC: "Alleen artsen mogen ASV zien",
    optionD: "Alleen Hamilton monteurs",
    correctOption: "A",
    explanation:
      "ASV vereist begrip van closed-loop ventilatie, instellingen en wanneer de mode niet geschikt is. Training is essentieel.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Welke waarde geeft % MinVol 50% bij IBW 60 kg?",
    optionA: "3 L/min",
    optionB: "6 L/min",
    optionC: "12 L/min",
    optionD: "0,5 L/min",
    correctOption: "A",
    explanation: "100% = 60 × 0,1 = 6 L/min. 50% daarvan = 3 L/min.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke longmechanische waarden gebruikt ASV voor sturing?",
    optionA: "Compliance, weerstand en auto-PEEP",
    optionB: "Alleen bloeddruk",
    optionC: "Alleen lichaamstemperatuur",
    optionD: "Alleen urineproductie",
    correctOption: "A",
    explanation:
      "ASV gebruikt gemeten longmechanica (compliance, weerstand, auto-PEEP) samen met patientinspanning voor closed-loop sturing.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "Obese patient post-cardiothoracaal chirurgie met lage FRC: waarom voorzichtig met ASV?",
    optionA: "Risico op derecruitment; soms expliciete TV/PEEP strategie nodig",
    optionB: "ASV werkt beter bij obesitas",
    optionC: "PEEP is contraindicated",
    optionD: "Hamilton ventilatoren ondersteunen obesitas niet",
    correctOption: "A",
    explanation:
      "Post-CTC patienten met lage FRC lopen derecruitment risico. Soms wil je expliciete controle over TV en PEEP in plaats van volledige automatisering.",
    category: "contra-indicaties",
    difficulty: 3,
  },
];
