import type { CorrectOption } from "../src/generated/prisma/enums";

export interface QuestionSeed {
  questionText: string;
  imageUrl?: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: CorrectOption;
  explanation: string;
  category: string;
  difficulty: number;
}

export const questions: QuestionSeed[] = [
  {
    questionText: "Wat betekent iASV in de context van Hamilton-beademing?",
    imageUrl: "/images/quiz/iasv-overview.svg",
    optionA: "Intelligent Adaptive Support Ventilation",
    optionB: "Intermittent Airway Support Ventilation",
    optionC: "Invasive Automatic Spontaneous Ventilation",
    optionD: "Integrated Alarm Safety Ventilation",
    correctOption: "A",
    explanation:
      "iASV staat voor Intelligent Adaptive Support Ventilation (Adaptive Support Ventilation). Het is een closed-loop ventilatiemodus die ademfrequentie, tidal volume en inspiratietijd automatisch aanpast.",
    category: "basis",
    difficulty: 1,
  },
  {
    questionText: "Op welke ventilatoren is iASV beschikbaar?",
    imageUrl: "/images/quiz/hamilton-ventilator.svg",
    optionA: "Alleen op Hamilton Medical ventilatoren",
    optionB: "Op alle ICU-ventilatoren",
    optionC: "Alleen op transportventilatoren",
    optionD: "Alleen op neonatale ventilatoren",
    correctOption: "A",
    explanation:
      "iASV is exclusief beschikbaar op Hamilton Medical ventilatoren (C1, C3, C6, T1, MR1). Andere merken bieden geen iASV-modus.",
    category: "basis",
    difficulty: 1,
  },
  {
    questionText: "Hoeveel hoofdparameters stelt de gebruiker typisch in bij iASV?",
    imageUrl: "/images/quiz/settings-panel.svg",
    optionA: "Drie: % MinVol, PEEP en Pasv limit",
    optionB: "Vijf: TV, RR, PEEP, FiO2 en I:E",
    optionC: "Twee: alleen PEEP en FiO2",
    optionD: "Zeven: alle conventionele parameters",
    correctOption: "A",
    explanation:
      "iASV vereenvoudigt ventilatie: de gebruiker stelt vooral % MinVol (doel-minuutvolume), PEEP en Pasv limit in. TV en RR worden automatisch bepaald.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Hoe wordt het doel-minuutvolume bij volwassenen berekend in iASV?",
    imageUrl: "/images/quiz/minvol-calc.svg",
    optionA: "0,1 L/kg ideaal lichaamsgewicht (IBW) × % MinVol",
    optionB: "0,5 L/kg actueel lichaamsgewicht × % MinVol",
    optionC: "6 ml/kg actueel gewicht × ademfrequentie",
    optionD: "Vast 8 L/min ongeacht gewicht",
    correctOption: "A",
    explanation:
      "Bij volwassenen: minuutvolume = 0,1 L/kg IBW. Bij 100% MinVol en IBW 70 kg is dat 7 L/min. Bij 50% MinVol is het 3,5 L/min.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Een volwassen patient heeft IBW 80 kg. Wat is het minuutvolume bij 100% MinVol?",
    optionA: "8 L/min",
    optionB: "4 L/min",
    optionC: "16 L/min",
    optionD: "0,8 L/min",
    correctOption: "A",
    explanation: "80 kg × 0,1 L/kg = 8 L/min bij 100% MinVol.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke ventilatiepatronen kan iASV automatisch afwisselen?",
    imageUrl: "/images/quiz/ventilation-modes.svg",
    optionA: "PCV, PSV en SIMV-P",
    optionB: "Alleen volume-gestuurd",
    optionC: "Alleen HFJV",
    optionD: "Alleen CPAP zonder druk",
    correctOption: "A",
    explanation:
      "iASV wisselt breath-by-breath tussen pressure-controlled ventilation (PCV), pressure support (PSV) en SIMV-P, afhankelijk van patientinspanning en longmechanica.",
    category: "basis",
    difficulty: 2,
  },
  {
    questionText: "Wat is een belangrijk voordeel van closed-loop ventilatie zoals iASV?",
    optionA: "Continue automatische aanpassing aan patient en longmechanica",
    optionB: "Geen monitoring meer nodig",
    optionC: "Vaste TV en RR ongeacht patient",
    optionD: "Werkt zonder flowsensor",
    correctOption: "A",
    explanation:
      "iASV past ademhalingspatroon continu aan op basis van gemeten longmechanica en patientinspanning, wat de klinische workload kan verlagen.",
    category: "basis",
    difficulty: 1,
  },
  {
    questionText: "Waarvoor dient de Pasv limit instelling?",
    imageUrl: "/images/quiz/pasv-limit.svg",
    optionA: "Maximale inspiriumdruk die iASV mag gebruiken",
    optionB: "Minimale PEEP waarde",
    optionC: "Maximale FiO2",
    optionD: "Expiratoire trigger gevoeligheid",
    correctOption: "A",
    explanation:
      "Pasv limit (passive limit) beperkt de maximale inspiriumdruk. Standaard vaak 30 cmH2O bij normale patienten, lager bij ARDS.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat is een gangbare startinstelling voor % MinVol bij een normale volwassen patient?",
    optionA: "100%",
    optionB: "30%",
    optionC: "200%",
    optionD: "0%",
    correctOption: "A",
    explanation:
      "100% MinVol is een veelgebruikte startwaarde. Bij ARDS wordt soms 120% gekozen; sommigen starten op 110% vanwege dead space.",
    category: "instellingen",
    difficulty: 1,
  },
  {
    questionText: "Waarom kan iASV NIET geschikt zijn bij een groot lek in het ademhalingscircuit?",
    imageUrl: "/images/quiz/leak-warning.svg",
    optionA: "De flowsensor meet onbetrouwbaar volume bij lekkage",
    optionB: "iASV werkt alleen bij hoge PEEP",
    optionC: "Hamilton ventilatoren ondersteunen geen lekkage",
    optionD: "iASV verhoogt automatisch FiO2 bij lek",
    correctOption: "A",
    explanation:
      "Bij lekkages (cuff leak, bronchopleurale fistel, open pneumothorax) is volume- en flowmeting onbetrouwbaar. iASV is dan gecontra-indiceerd.",
    category: "contra-indicaties",
    difficulty: 2,
  },
  {
    questionText: "Welke situatie is een contra-indicatie voor iASV?",
    optionA: "Ernstige metabole acidose met zeer hoge ventilatiebehoefte",
    optionB: "Postoperatieve patient zonder complicaties",
    optionC: "Normale spontane ademhaling",
    optionD: "Milde COPD",
    correctOption: "A",
    explanation:
      "Bij ernstige metabole acidose wil je soms expliciet hoge RR/TV instellen. iASV stuurt automatisch en laat niet altijd toe wat klinisch gewenst is.",
    category: "contra-indicaties",
    difficulty: 3,
  },
  {
    questionText: "Waarom is iASV problematisch bij abnormale ademhalingspatronen?",
    optionA: "Het algoritme kan niet goed interpreteren wat gewenst ademhalingsgedrag is",
    optionB: "iASV schakelt automatisch uit bij Cheyne-Stokes",
    optionC: "De ventilator geeft dan alleen CPAP",
    optionD: "FiO2 kan niet worden aangepast",
    correctOption: "A",
    explanation:
      "Bij abnormale patronen (Cheyne-Stokes, frequent apnea) interpreteert iASV patientinspanning en mechanica verkeerd.",
    category: "contra-indicaties",
    difficulty: 2,
  },
  {
    questionText: "Wat meet de proximale flowsensor bij Hamilton ventilatoren?",
    imageUrl: "/images/quiz/proximal-sensor.svg",
    optionA: "Flow en volume dicht bij de patient (Y-stuk)",
    optionB: "Alleen druk in het expiratieventiel",
    optionC: "Alleen bloeddruk",
    optionD: "Alleen FiO2 aan de machinezijde",
    correctOption: "A",
    explanation:
      "De proximale flowsensor meet flow en volume aan de patientzijde, wat nauwkeuriger is dan alleen ventilator-side meting, vooral bij lekkage.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is RCexp in de context van iASV 1.1?",
    optionA: "Expiratoire tijdconstante van de longen",
    optionB: "Residuale CO2 in expirat",
    optionC: "Respiratoire compliance van de thoraxwand",
    optionD: "Ratio compressie/expansie",
    correctOption: "A",
    explanation:
      "iASV 1.1 meet breath-by-breath RCexp (expiratoire tijdconstante) om longmechanica te beoordelen en optimale RR/TV te kiezen.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Welk wiskundig model ligt ten grondslag aan iASV?",
    imageUrl: "/images/quiz/otis-equation.svg",
    optionA: "Aangepaste Otis-vergelijking",
    optionB: "Bernoulli-vergelijking",
    optionC: "Starling-vergelijking",
    optionD: "Boyle's wet alleen",
    correctOption: "A",
    explanation:
      "iASV gebruikt een aangepaste Otis-vergelijking om het ademhalingspatroon te vinden met minste ademhalingswerk bij het gekozen minuutvolume.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Wat is het doel van lung-protective strategie in iASV?",
    imageUrl: "/images/quiz/lung-protective.svg",
    optionA: "Barotrauma, volutrauma en AutoPEEP voorkomen",
    optionB: "Maximaal minuutvolume leveren",
    optionC: "Altijd hoge plateau druk",
    optionD: "Spontane ademhaling volledig onderdrukken",
    correctOption: "A",
    explanation:
      "iASV streeft naar lung-protective ventilatie: voorkomen van te grote breaths, te hoge drukken, apneu, tachypneu en dead-space ventilatie.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is AutoPEEP?",
    optionA: "Positieve expiratoire druk door incomplete expiratie",
    optionB: "Automatisch ingestelde PEEP door de verpleegkundige",
    optionC: "PEEP gemeten in het bloed",
    optionD: "FiO2 die automatisch stijgt",
    correctOption: "A",
    explanation:
      "AutoPEEP (intrinsic PEEP) ontstaat wanneer expiratie niet afloopt voor de volgende inspiratie. iASV probeert dit te minimaliseren.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wanneer in het ventilatieproces kan iASV worden gebruikt?",
    imageUrl: "/images/quiz/intubation-extubation.svg",
    optionA: "Van intubatie tot extubatie",
    optionB: "Alleen tijdens weaning",
    optionC: "Alleen eerste 24 uur",
    optionD: "Alleen bij NIV",
    correctOption: "A",
    explanation:
      "iASV kan worden gebruikt gedurende het hele beademingsproces: initiatie, onderhoud en weaning, zowel bij passieve als actieve patienten.",
    category: "weaning",
    difficulty: 1,
  },
  {
    questionText: "Hoe kan iASV het weaningproces ondersteunen?",
    optionA: "Door % MinVol geleidelijk te verlagen naarmate de patient meer spontaan ademt",
    optionB: "Door automatisch te extuberen",
    optionC: "Door PEEP altijd op 0 te zetten",
    optionD: "Door sedatie automatisch te verhogen",
    correctOption: "A",
    explanation:
      "Bij afnemende beademingsbehoefte kan % MinVol omlaag. iASV past RR/TV aan terwijl de patient meer spontane ademhaling levert.",
    category: "weaning",
    difficulty: 2,
  },
  {
    questionText: "Wat gebeurt er als een patient op iASV meer spontaan gaat ademen?",
    optionA: "iASV geeft meer drukondersteuning (PSV-achtig) en past RR aan",
    optionB: "iASV stopt volledig met beademen",
    optionC: "iASV verhoogt altijd PEEP met 5 cmH2O",
    optionD: "iASV schakelt over naar HFNC",
    correctOption: "A",
    explanation:
      "Bij spontane inspanning schakelt iASV naar meer ondersteunende modi (PSV) en past frequentie en volume aan binnen het doel-minuutvolume.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is IntelliVent-iASV?",
    imageUrl: "/images/quiz/intellivent.svg",
    optionA: "Uitbreiding van iASV die ook FiO2 en PEEP automatisch stuurt",
    optionB: "Een apart merk ventilator",
    optionC: "Alleen een alarmfunctie",
    optionD: "Een mode voor thuisbeademing",
    correctOption: "A",
    explanation:
      "IntelliVent-iASV breidt iASV uit met automatische sturing van oxygenatie (FiO2) en PEEP op basis van SpO2/PaO2 en andere parameters.",
    category: "basis",
    difficulty: 2,
  },
  {
    questionText: "Welke patientpopulatie kan iASV ondersteunen?",
    optionA: "Volwassenen en pediatrische patienten",
    optionB: "Alleen neonaten onder 3 kg",
    optionC: "Alleen traumapatiente",
    optionD: "Alleen COPD-patienten",
    correctOption: "A",
    explanation:
      "iASV kan bij volwassenen en pediatrische patienten worden gebruikt. Pediatrisch minuutvolume wordt anders berekend (0,3 L/kg bij 3 kg tot 0,1 L/kg bij 30 kg).",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Hoe wordt minuutvolume bij een kind van 10 kg (pediatrisch) benaderd in iASV?",
    optionA: "Via een pediatrische schaal tussen 0,3 en 0,1 L/kg IBW",
    optionB: "Altijd 6 L/min vast",
    optionC: "Via actueel gewicht × 0,5 L/kg",
    optionD: "Niet mogelijk in iASV",
    correctOption: "A",
    explanation:
      "Pediatrisch: minuutvolume loopt van 0,3 L/kg bij IBW 3 kg naar 0,1 L/kg bij IBW 30 kg. Bij 10 kg zit je tussen die waarden in.",
    category: "instellingen",
    difficulty: 3,
  },
  {
    questionText: "Wat is volutrauma?",
    optionA: "Longschade door te grote tidal volumes",
    optionB: "Schade door te lage FiO2",
    optionC: "Infectie door beademing",
    optionD: "Droge slijmvliezen door HFNC",
    correctOption: "A",
    explanation:
      "Volutrauma is longschade door overdistensie (te grote TV). iASV probeert dit te voorkomen via lung-protective limieten.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Wat is barotrauma?",
    optionA: "Longschade door te hoge drukken in het ademhalingsstelsel",
    optionB: "Schade door zuurstoftoxiciteit",
    optionC: "Spiervermoeidheid door hoesten",
    optionD: "Allergische reactie op filters",
    correctOption: "A",
    explanation:
      "Barotrauma ontstaat door excessieve druk (bijv. pneumothorax). Pasv limit helpt dit te beperken.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Waarom kan iASV mechanical power verlagen t.o.v. conventionele modi?",
    imageUrl: "/images/quiz/mechanical-power.svg",
    optionA: "Het kiest lagere optimale RR en drukken via het algoritme",
    optionB: "Het gebruikt geen drukventilatie",
    optionC: "Het schakelt ventilatie elke 4 uur uit",
    optionD: "Het verhoogt altijd TV",
    correctOption: "A",
    explanation:
      "iASV 1.1 selecteert frequentie en volume met lagere ademhalingskracht en mechanical power, wat gunstig kan zijn voor longbescherming.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Wat is flow trigger?",
    optionA: "Start inspiratie bij een bepaalde flowafwijking t.o.v. baseline",
    optionB: "Automatische PEEP-verhoging",
    optionC: "Expiratoire pauze instelling",
    optionD: "Maximale inspiratieflow",
    correctOption: "A",
    explanation:
      "Flow trigger bepaalt wanneer een inspiratoire effort wordt herkend. Te gevoelig kan auto-triggering geven; te ongevoelig vertraagt trigger.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat doet P-ramp (pressure ramp)?",
    optionA: "Bepaalt hoe snel inspiriumdruk wordt opgebouwd",
    optionB: "Verhoogt PEEP bij desaturatie",
    optionC: "Meet plateau druk",
    optionD: "Stelt ETS in",
    correctOption: "A",
    explanation:
      "P-ramp regelt de snelheid van drukopbouw. Langere ramp kan comfort verbeteren; kortere ramp kan sneller volume leveren.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat is ETS (Expiratory Trigger Sensitivity)?",
    imageUrl: "/images/quiz/breath-cycle.svg",
    optionA: "Gevoeligheid waarmee inspiratie wordt beeindigd",
    optionB: "Expiratoire PEEP waarde",
    optionC: "Trigger voor hartfrequentie",
    optionD: "ETS is hetzelfde als I:E ratio",
    correctOption: "A",
    explanation:
      "ETS bepaalt wanneer de ventilator van inspiratie naar expiratie schakelt bij druk- of volume-gestuurde breaths.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke instelling beinvloedt vooral oxygenatie in standaard iASV (niet IntelliVent)?",
    optionA: "PEEP en FiO2 (handmatig door gebruiker)",
    optionB: "Alleen % MinVol",
    optionC: "Alleen Pasv limit",
    optionD: "Alleen flow trigger",
    correctOption: "A",
    explanation:
      "In standaard iASV stuurt de gebruiker oxygenatie via PEEP en FiO2. % MinVol regelt vooral ventilatie (CO2). IntelliVent automatiseert ook oxygenatie.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke instelling regelt vooral alveolaire ventilatie (CO2) in iASV?",
    optionA: "% MinVol",
    optionB: "Alleen PEEP",
    optionC: "Alleen FiO2",
    optionD: "Alleen humidifier temperatuur",
    correctOption: "A",
    explanation:
      "% MinVol bepaalt het doel-minuutvolume en daarmee in belangrijke mate alveolaire ventilatie en CO2-eliminatie.",
    category: "instellingen",
    difficulty: 1,
  },
  {
    questionText: "Patient met ARDS: welke % MinVol startwaarde is vaak geschikter dan 100%?",
    optionA: "120%",
    optionB: "50%",
    optionC: "10%",
    optionD: "300%",
    correctOption: "A",
    explanation:
      "Bij ARDS wordt vaak 120% MinVol als startpunt genoemd vanwege verhoogd dead space en verhoogde ventilatiebehoefte.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Waarom is iASV soms minder geschikt bij restrictieve longziekte met zeer lage TV-behoefte?",
    optionA: "Je kunt TV en RR niet direct handmatig forceren",
    optionB: "Hamilton ventilatoren ondersteunen restrictieve ziekte niet",
    optionC: "iASV geeft altijd TV van 10 ml/kg",
    optionD: "PEEP werkt niet bij restrictieve ziekte",
    correctOption: "A",
    explanation:
      "Bij restrictieve longziekte wil je soms expliciet lage TV. iASV stuurt automatisch en laat beperkte directe TV/RR-controle toe.",
    category: "contra-indicaties",
    difficulty: 3,
  },
  {
    questionText: "Wat is dead-space ventilatie?",
    optionA: "Ventilatie van luchtwegen zonder gasuitwisseling in alveoli",
    optionB: "Ventilatie met 0 PEEP",
    optionC: "Apneu per minuut",
    optionD: "Ventilatie zonder humidificatie",
    correctOption: "A",
    explanation:
      "Dead-space ventilatie levert volume aan niet-gasuitwisselende delen. iASV probeert inefficinte hoge frequenties met kleine TV te vermijden.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Welke sensor is essentieel voor accurate iASV-werking?",
    imageUrl: "/images/quiz/proximal-sensor.svg",
    optionA: "Proximale flowsensor",
    optionB: "Transcutane CO2 sensor alleen",
    optionC: "EKG elektrode",
    optionD: "Temperatuursensor buiten circuit",
    correctOption: "A",
    explanation:
      "iASV vertrouwt op nauwkeurige flow/volumemeting via de proximale sensor voor closed-loop sturing.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is het verschil tussen iASV 1.0 en iASV 1.1?",
    optionA: "iASV 1.1 gebruikt RCexp meting en optimaliseert mechanical power beter",
    optionB: "iASV 1.0 werkt alleen bij kinderen",
    optionC: "iASV 1.1 heeft geen proximale sensor nodig",
    optionD: "Er is geen verschil",
    correctOption: "A",
    explanation:
      "iASV 1.1 meet RCexp breath-by-breath en kiest frequentie/volume met lagere mechanical power. Dit is standaard op moderne Hamilton ventilatoren.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Welke parameter mag je NIET direct instellen in iASV?",
    optionA: "Respiratory rate (RR) als vaste waarde",
    optionB: "PEEP",
    optionC: "FiO2",
    optionD: "% MinVol",
    correctOption: "A",
    explanation:
      "In iASV stel je geen vaste RR of TV in; die worden automatisch bepaald. PEEP, FiO2 en % MinVol wel.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Patient met bronchopleurale fistel (BPF): waarom iASV vermijden?",
    imageUrl: "/images/quiz/leak-warning.svg",
    optionA: "Groot lek maakt volumemeting en closed-loop sturing onbetrouwbaar",
    optionB: "BPF vereist altijd NIV",
    optionC: "iASV verhoogt fistel automatisch",
    optionD: "Hamilton ventilatoren detecteren BPF niet",
    correctOption: "A",
    explanation:
      "BPF veroorzaakt groot lek. iASV kan volume en patientinspanning niet betrouwbaar meten, waardoor onveilige sturing mogelijk is.",
    category: "contra-indicaties",
    difficulty: 3,
  },
  {
    questionText: "Wat is SIMV-P in de context van iASV?",
    optionA: "Synchronized intermittent mandatory pressure breaths",
    optionB: "Simple manual ventilation protocol",
    optionC: "Spontaneous mode without monitoring",
    optionD: "Safety mode for power failure",
    correctOption: "A",
    explanation:
      "SIMV-P combineert mandatory pressure breaths met ruimte voor spontane ademhaling. iASV kan dit patroon automatisch inzetten.",
    category: "basis",
    difficulty: 2,
  },
  {
    questionText: "Waarom is IBW (ideaal lichaamsgewicht) belangrijk voor iASV?",
    imageUrl: "/images/quiz/minvol-calc.svg",
    optionA: "Minuutvolume wordt op IBW gebaseerd, niet actueel gewicht",
    optionB: "IBW bepaalt alleen FiO2",
    optionC: "IBW is alleen voor pediatrie",
    optionD: "IBW wordt niet gebruikt in iASV",
    correctOption: "A",
    explanation:
      "iASV berekent doel-minuutvolume op basis van IBW. Bij obesitas voorkomt dit overventilatie op basis van actueel gewicht.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke complicatie kan optreden bij te hoge Pasv limit?",
    optionA: "Barotrauma door te hoge drukken",
    optionB: "Te lage PEEP",
    optionC: "Apneu door te lage TV",
    optionD: "Geen enkele",
    correctOption: "A",
    explanation:
      "Een te hoge Pasv limit staat hogere inspiriumdrukken toe, wat barotrauma kan bevorderen. Stel conservatief in bij ARDS.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat doet iASV bij apneu van de patient?",
    optionA: "Levert mandatory breaths om minuutvolume te halen",
    optionB: "Schakelt ventilator uit",
    optionC: "Verlaagt PEEP naar 0",
    optionD: "Wacht 10 minuten",
    correctOption: "A",
    explanation:
      "Bij apneu levert iASV mandatory breaths (PCV) om het ingestelde minuutvolume te behalen.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Welke rol speelt PEEP in iASV?",
    imageUrl: "/images/quiz/peep-diagram.svg",
    optionA: "Recruitment en oxygenatie ondersteunen",
    optionB: "Direct CO2 verwijderen",
    optionC: "RR automatisch verdubbelen",
    optionD: "ETS vervangen",
    correctOption: "A",
    explanation:
      "PEEP ondersteunt alveolaire recruitment en oxygenatie. In standaard iASV stel je PEEP handmatig in (IntelliVent kan automatisch).",
    category: "instellingen",
    difficulty: 1,
  },
  {
    questionText: "Waarom monitort de verpleegkundige/arts iASV-patienten nog steeds?",
    optionA: "iASV vereist klinische beoordeling en alarms opvolging",
    optionB: "iASV werkt volledig zonder supervisie",
    optionC: "Alleen voor administratie",
    optionD: "Monitoring is verboden bij iASV",
    correctOption: "A",
    explanation:
      "iASV automatiseert veel, maar vereist nog steeds monitoring van saturatie, CO2, drukken, patientcomfort en contra-indicaties.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Welke start-PEEP wordt vaak genoemd als richtlijn bij iASV?",
    optionA: "5 cmH2O of volgens ICU-protocol",
    optionB: "0 cmH2O altijd",
    optionC: "20 cmH2O standaard",
    optionD: "PEEP is niet instelbaar",
    correctOption: "A",
    explanation:
      "5 cmH2O of het lokale ICU-protocol is een veelgebruikte PEEP-startwaarde, aangepast aan patient en pathologie.",
    category: "instellingen",
    difficulty: 1,
  },
  {
    questionText: "Open pneumothorax: waarom is iASV gecontra-indiceerd?",
    imageUrl: "/images/quiz/leak-warning.svg",
    optionA: "Massief lek maakt ventilatiesturing onbetrouwbaar",
    optionB: "Pneumothorax vereist altijd CPAP",
    optionC: "iASV verhoogt automatisch thoraxdrain",
    optionD: "FiO2 kan niet worden ingesteld",
    correctOption: "A",
    explanation:
      "Bij open pneumothorax is er een groot lek. iASV kan volume niet betrouwbaar meten; kies een andere mode tot het lek is opgelost.",
    category: "contra-indicaties",
    difficulty: 2,
  },
  {
    questionText: "Hoe vaardig moet ICU-personeel zijn met iASV?",
    optionA: "Getraind in iASV-principes, instellingen en beperkingen",
    optionB: "Geen training nodig",
    optionC: "Alleen artsen mogen iASV zien",
    optionD: "Alleen Hamilton monteurs",
    correctOption: "A",
    explanation:
      "iASV vereist begrip van closed-loop ventilatie, instellingen en wanneer de mode niet geschikt is. Training is essentieel.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Welke waarde geeft % MinVol 50% bij IBW 60 kg?",
    optionA: "3 L/min",
    optionB: "6 L/min",
    optionC: "12 L/min",
    optionD: "0,5 L/min",
    correctOption: "A",
    explanation: "100% = 60 × 0,1 = 6 L/min. 50% daarvan = 3 L/min.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Welke longmechanische waarden gebruikt iASV voor sturing?",
    optionA: "Compliance, weerstand en auto-PEEP",
    optionB: "Alleen bloeddruk",
    optionC: "Alleen lichaamstemperatuur",
    optionD: "Alleen urineproductie",
    correctOption: "A",
    explanation:
      "iASV gebruikt gemeten longmechanica (compliance, weerstand, auto-PEEP) samen met patientinspanning voor closed-loop sturing.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "Obese patient post-cardiothoracaal chirurgie met lage FRC: waarom voorzichtig met iASV?",
    optionA: "Risico op derecruitment; soms expliciete TV/PEEP strategie nodig",
    optionB: "iASV werkt beter bij obesitas",
    optionC: "PEEP is contraindicated",
    optionD: "Hamilton ventilatoren ondersteunen obesitas niet",
    correctOption: "A",
    explanation:
      "Post-CTC patienten met lage FRC lopen derecruitment risico. Soms wil je expliciete controle over TV en PEEP in plaats van volledige automatisering.",
    category: "contra-indicaties",
    difficulty: 3,
  },
  {
    questionText: "Welke ademhalingsparameter past iASV automatisch aan naast RR en TV?",
    optionA: "Inspiratietijd (Ti)",
    optionB: "Alleen humidifiertemperatuur",
    optionC: "Cuffdruk",
    optionD: "Bloeddrukdoel",
    correctOption: "A",
    explanation:
      "iASV stuurt RR, TV en inspiratietijd automatisch. Ti past mee aan het gekozen ventilatiepatroon en longmechanica.",
    category: "basis",
    difficulty: 2,
  },
  {
    questionText: "Waarom gebruikt iASV vooral druk-gestuurde breaths (PCV/PSV) in plaats van volume-gestuurd?",
    optionA: "Druk-gestuurd past beter bij variabele weerstand en lung-protective sturing",
    optionB: "Volume-gestuurd is op Hamilton ventilatoren niet mogelijk",
    optionC: "iASV werkt alleen zonder PEEP",
    optionD: "Druk-gestuurd verhoogt altijd het minuutvolume",
    correctOption: "A",
    explanation:
      "iASV kiest PCV, PSV en SIMV-P. Druk-gestuurde breaths passen zich aan compliance en weerstand aan binnen de Pasv limit.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "Patient IBW 75 kg, % MinVol 80%. Wat is het doel-minuutvolume?",
    optionA: "6 L/min",
    optionB: "7,5 L/min",
    optionC: "4 L/min",
    optionD: "8 L/min",
    correctOption: "A",
    explanation: "100% = 75 × 0,1 = 7,5 L/min. 80% daarvan = 6 L/min.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat is driving pressure in mechanische ventilatie?",
    optionA: "Plateaudruk minus PEEP",
    optionB: "Peak pressure minus FiO2",
    optionC: "Minuutvolume gedeeld door RR",
    optionD: "PEEP plus Pasv limit",
    correctOption: "A",
    explanation:
      "Driving pressure (ΔP) = plateau druk − PEEP. iASV beperkt drukken via Pasv limit en lung-protective algoritme, wat ΔP kan beinvloeden.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Bij ARDS: welke Pasv limit is vaak conservatiever dan 30 cmH2O?",
    optionA: "20–25 cmH2O, afgestemd op longbescherming",
    optionB: "50 cmH2O standaard",
    optionC: "Pasv limit is bij ARDS niet instelbaar",
    optionD: "0 cmH2O",
    correctOption: "A",
    explanation:
      "Bij ARDS worden lagere inspiriumdrukken nagestreefd. Pasv limit wordt vaak lager gezet dan bij patienten zonder restrictieve longschade.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Hoe titrer je % MinVol bij een te hoge EtCO2 of PaCO2?",
    optionA: "Verhoog % MinVol in stappen en evalueer ABG/EtCO2",
    optionB: "Verlaag PEEP met 10 cmH2O",
    optionC: "Zet Pasv limit op maximum",
    optionD: "Schakel over naar CPAP zonder ondersteuning",
    correctOption: "A",
    explanation:
      "% MinVol regelt het doel-minuutvolume en daarmee CO2-eliminatie. Verhoog geleidelijk en monitor effect op CO2 en drukken.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat is permissive hypercapnie in relatie tot iASV?",
    optionA: "Bewust accepteren van licht verhoogde PaCO2 om longbescherming te bevorderen",
    optionB: "Altijd % MinVol op 200% zetten",
    optionC: "FiO2 op 100% houden",
    optionD: "PEEP altijd op 0 cmH2O",
    correctOption: "A",
    explanation:
      "Bij ARDS kan een lagere % MinVol en acceptatie van milde hypercapnie longbeschermend zijn, mits hemodynamisch en neurologisch verantwoord.",
    category: "kliniek",
    difficulty: 3,
  },
  {
    questionText: "Welke patient met COPD vraagt extra aandacht bij iASV?",
    optionA: "Patient met risico op AutoPEEP door lange expiratietijd",
    optionB: "Patient zonder longziekte",
    optionC: "Patient met normale compliance",
    optionD: "Patient die volledig apneu is zonder obstructie",
    correctOption: "A",
    explanation:
      "COPD-patienten hebben vaak verlengde expiratie. iASV minimaliseert AutoPEEP, maar monitor expiratoire flow en totale PEEP nauwkeurig.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is patient-ventilator asynchronie?",
    optionA: "Mismatch tussen patientinspanning en ventilator timing/volume",
    optionB: "Gelijke RR en TV elke ademhaling",
    optionC: "Automatische PEEP-verhoging door iASV",
    optionD: "Alleen een sensorfout in FiO2",
    correctOption: "A",
    explanation:
      "Asynchronie (bijv. double triggering, ineffective effort) kan optreden bij elke mode. iASV past breath-by-breath aan, maar vereist klinische evaluatie.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat kan double triggering veroorzaken tijdens iASV?",
    optionA: "Te gevoelige flow trigger of korte inspiratietijd t.o.v. patienteffort",
    optionB: "Te hoge PEEP alleen",
    optionC: "Te lage FiO2",
    optionD: "Gebruik van proximale sensor",
    correctOption: "A",
    explanation:
      "Double triggering ontstaat wanneer de patient twee keer triggert binnen een korte periode. Check triggergevoeligheid, sedatie en ventilatorgrafieken.",
    category: "kliniek",
    difficulty: 3,
  },
  {
    questionText: "Welke SpO2-doelstelling stuurt IntelliVent-iASV typisch aan?",
    optionA: "Instelbaar SpO2-doel (bijv. 88–95% afhankelijk van protocol)",
    optionB: "Altijd 100% SpO2",
    optionC: "SpO2 wordt niet gebruikt",
    optionD: "Alleen EtCO2 als oxygenatiedoel",
    correctOption: "A",
    explanation:
      "IntelliVent-iASV past FiO2 en PEEP aan op basis van SpO2 (en andere parameters) rond een ingesteld oxygenatiedoel.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat is het voordeel van IntelliVent-iASV t.o.v. standaard iASV bij instabiele oxygenatie?",
    optionA: "Automatische FiO2/PEEP-titration naast ventilatiesturing",
    optionB: "Geen monitoring meer nodig",
    optionC: "Vaste TV en RR ongeacht patient",
    optionD: "Werkt zonder saturatiemeter",
    correctOption: "A",
    explanation:
      "IntelliVent-iASV automatiseert ook oxygenatie, wat de werklast kan verlagen bij wisselende oxygenatiebehoefte.",
    category: "basis",
    difficulty: 2,
  },
  {
    questionText: "Waarom is IBW bij obesitas belangrijker dan actueel lichaamsgewicht in iASV?",
    optionA: "Overventilatie op basis van vetmassa wordt voorkomen",
    optionB: "Obesitas verandert alleen FiO2",
    optionC: "iASV gebruikt actueel gewicht × 0,5 L/kg",
    optionD: "IBW geldt niet voor volwassenen",
    correctOption: "A",
    explanation:
      "Minuutvolume = 0,1 L/kg IBW × % MinVol. IBW schat longgrootte beter dan actueel gewicht bij obesitas.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "IBW man, lengte 180 cm (Devine): ongeveer welk gewicht?",
    optionA: "75 kg",
    optionB: "100 kg",
    optionC: "50 kg",
    optionD: "90 kg",
    correctOption: "A",
    explanation:
      "Devine man: IBW ≈ 50 + 0,91 × (cm − 152,4). Bij 180 cm ≈ 75 kg. iASV gebruikt IBW voor minuutvolume.",
    category: "instellingen",
    difficulty: 3,
  },
  {
    questionText: "Welke Hamilton ventilator is bedoeld voor intrahospitale transport?",
    optionA: "Hamilton-T1",
    optionB: "Alleen Hamilton-C1 zonder batterij",
    optionC: "Geen Hamilton ondersteunt transport",
    optionD: "Alleen neonatale ventilatoren",
    correctOption: "A",
    explanation:
      "Hamilton-T1 en MR1 zijn transport/MRI-ventilatoren waar iASV ook beschikbaar kan zijn, naast ICU-modellen C1/C3/C6.",
    category: "basis",
    difficulty: 1,
  },
  {
    questionText: "Wat gebeurt er met iASV bij een passieve, volledig sedated patient?",
    optionA: "iASV levert vooral mandatory PCV-breaths om minuutvolume te halen",
    optionB: "iASV schakelt automatisch uit",
    optionC: "iASV geeft alleen CPAP",
    optionD: "PEEP wordt altijd 0",
    correctOption: "A",
    explanation:
      "Zonder spontane inspanning levert iASV mandatory pressure-controlled breaths volgens het ingestelde % MinVol.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is RSBI (Rapid Shallow Breathing Index) nuttig voor bij weaning?",
    optionA: "RR/TV ratio als indicator voor extubatie-geschiktheid",
    optionB: "PEEP minus AutoPEEP",
    optionC: "FiO2 gedeeld door SpO2",
    optionD: "Pasv limit × % MinVol",
    correctOption: "A",
    explanation:
      "RSBI = ademfrequentie / tidal volume (L). Lage waarden (<105) suggereren betere extubatiekans; combineer met klinische beoordeling en iASV-weaning.",
    category: "weaning",
    difficulty: 2,
  },
  {
    questionText: "Hoe start je weaning met iASV praktisch?",
    optionA: "Verlaag % MinVol geleidelijk bij adequate spontane ademhaling",
    optionB: "Verhoog % MinVol elke uur",
    optionC: "Zet Pasv limit op 50 cmH2O",
    optionD: "Schakel direct uit naar kamerlucht",
    correctOption: "A",
    explanation:
      "Weaning: % MinVol stapsgewijs omlaag terwijl iASV RR/TV aanpast en spontane inspanning toeneemt.",
    category: "weaning",
    difficulty: 1,
  },
  {
    questionText: "Wanneer overweeg je iASV tijdelijk te verlaten voor een SBT?",
    optionA: "Bij extubatiebeoordeling volgens lokaal protocol (T-piece/PS trial)",
    optionB: "Nooit; iASV vervangt elke SBT",
    optionC: "Alleen bij neonaten",
    optionD: "Alleen als FiO2 21% is",
    correctOption: "A",
    explanation:
      "iASV kan het grootste deel van weaning ondersteunen, maar sommige protocollen gebruiken nog een aparte SBT voordat extubeert wordt.",
    category: "weaning",
    difficulty: 2,
  },
  {
    questionText: "Wat meet plateau druk en waarom is het relevant bij iASV?",
    optionA: "Druk na inspiratiepauze; schatting alveolaire druk en lung stretch",
    optionB: "Druk in expiratieventiel alleen",
    optionC: "Arteriële bloeddruk",
    optionD: "Temperatuur beademingsgas",
    correctOption: "A",
    explanation:
      "Plateau druk (met inspiratiepauze) helpt barotrauma/volutrauma te beoordelen. iASV beperkt drukken, maar plateau blijft klinisch relevant.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Waarom kan te gevoelige flow trigger problematisch zijn in iASV?",
    optionA: "Auto-triggering en asynchronie door circuit/lekkage of cardiale oscillaties",
    optionB: "iASV werkt dan alleen in SIMV",
    optionC: "PEEP kan niet worden ingesteld",
    optionD: "Proximale sensor schakelt uit",
    correctOption: "A",
    explanation:
      "Te gevoelige trigger kan extra breaths geven zonder patienteffort (auto-triggering), wat RR/TV en CO2 beinvloedt.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Wat is ineffective triggering?",
    optionA: "Patientinspanning zonder ventilatorresponse",
    optionB: "Ventilator ademt zonder patient",
    optionC: "PEEP die automatisch stijgt",
    optionD: "FiO2 die daalt bij desaturatie",
    correctOption: "A",
    explanation:
      "Ineffective efforts belasten de patient zonder ventilatie. Beoordeel grafieken, sedatie, AutoPEEP en triggerinstellingen.",
    category: "kliniek",
    difficulty: 3,
  },
  {
    questionText: "Welke situatie vraagt voorzichtigheid met iASV bij status asthmaticus?",
    optionA: "Ernstige obstructie met lang expiratie en AutoPEEP-risico",
    optionB: "Mild postoperatief zonder obstructie",
    optionC: "Normale compliance zonder wheezing",
    optionD: "Patient volledig apneu zonder obstructie",
    correctOption: "A",
    explanation:
      "Bij ernstig astma kan expliciete controle over RR, I:E en expiratietijd gewenst zijn. iASV stuurt automatisch; monitor AutoPEEP en asynchronie.",
    category: "contra-indicaties",
    difficulty: 3,
  },
  {
    questionText: "Traumatisch hersenletsel (TBI): waarom soms voorzichtig met iASV?",
    optionA: "Strikte PaCO2-doelen kunnen handmatige RR/TV-controle vereisen",
    optionB: "iASV verhoogt altijd intracraniële druk",
    optionC: "PEEP is contraindicated bij TBI",
    optionD: "Hamilton ventilatoren werken niet bij neurologie",
    correctOption: "A",
    explanation:
      "Bij TBI wil men soms strakke CO2-sturing. iASV automatiseert RR/TV; overweeg of expliciete controle nodig is volgens neuroprotocol.",
    category: "contra-indicaties",
    difficulty: 3,
  },
  {
    questionText: "Wat is het effect van koorts op ventilatiebehoefte in iASV?",
    optionA: "Verhoogde CO2-productie kan hogere % MinVol vereisen",
    optionB: "Geen effect op minuutvolume",
    optionC: "iASV verlaagt automatisch % MinVol bij koorts",
    optionD: "Alleen FiO2 stijgt",
    correctOption: "A",
    explanation:
      "Koorts verhoogt metabole behoefte en CO2-productie. % MinVol kan omhoog moeten om PaCO2/EtCO2 binnen doel te houden.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Pijn of onrust bij beademde patient: invloed op iASV?",
    optionA: "Meer spontane inspanning; iASV schakelt naar meer PSV-achtige ondersteuning",
    optionB: "iASV schakelt permanent uit",
    optionC: "Pasv limit wordt automatisch 0",
    optionD: "RR wordt vast op 4/min gezet",
    correctOption: "A",
    explanation:
      "Toegenomen patientinspanning beinvloedt het breath-by-breath patroon. Behandel ook pijn/sedatie; monitor asynchronie.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is static compliance (Cstat)?",
    optionA: "Δvolume / Δdruk tussen PEEP en plateau",
    optionB: "RR gedeeld door TV",
    optionC: "FiO2 × PEEP",
    optionD: "Expiratoire weerstand alleen",
    correctOption: "A",
    explanation:
      "Cstat = tidal volume / (plateau − PEEP). iASV gebruikt compliance-informatie voor closed-loop sturing van RR en TV.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Wat is airway resistance (Raw) en waarom relevant voor iASV?",
    optionA: "Drukgradient flow; beinvloedt benodigde inspiriumdruk en timing",
    optionB: "Alleen cuffdruk",
    optionC: "Hemoglobine concentratie",
    optionD: "Urineproductie per uur",
    correctOption: "A",
    explanation:
      "Verhoogde Raw (bijv. bronchospasm, kleine tube) vraagt hogere drukken en kan I:E beinvloeden. iASV past patroon aan gemeten mechanica aan.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "Kleine endotracheale tube (bijv. 6.0 mm): effect op iASV?",
    optionA: "Hogere weerstand; mogelijk hogere drukken en aangepast RR/TV",
    optionB: "Geen effect op ventilatie",
    optionC: "iASV werkt niet met tubes < 8.0 mm",
    optionD: "PEEP wordt automatisch uitgeschakeld",
    correctOption: "A",
    explanation:
      "Smalle tubes verhogen Raw. iASV kan hogere inspiriumdrukken nodig hebben binnen Pasv limit; monitor drukken en CO2.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "HME-filter vóór proximale sensor: waarom vermijden bij iASV?",
    optionA: "Extra dead space en mogelijke meet-/triggerproblemen",
    optionB: "Verplicht volgens Hamilton",
    optionC: "Verlaagt PEEP altijd",
    optionD: "Verhoogt IBW",
    correctOption: "A",
    explanation:
      "HME vergroot dead space en kan flowmeting/trigger beinvloeden. Volg Hamilton-richtlijn voor circuitopbouw rond proximale sensor.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "Wat is intrinsic PEEP (AutoPEEP) meting belangrijk voor?",
    optionA: "Inschatten totale expiratoire druk en risico op incomplete expiratie",
    optionB: "Alleen FiO2 titratie",
    optionC: "IBW berekening",
    optionD: "Cuffdruk instelling",
    correctOption: "A",
    explanation:
      "Totale PEEP = set PEEP + AutoPEEP. iASV minimaliseert AutoPEEP, maar meting blijft essentieel bij obstructieve pathologie.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Prone positioning bij ARDS op iASV: wat doe je met % MinVol?",
    optionA: "Herbeoordeel % MinVol en oxygenatie na repositionering",
    optionB: "Altijd % MinVol op 10% zetten",
    optionC: "Pasv limit verhogen naar 50 cmH2O",
    optionD: "Niets; prone heeft geen effect",
    correctOption: "A",
    explanation:
      "Prone kan compliance, oxygenatie en CO2 beinvloeden. Her-evalueer % MinVol, PEEP/FiO2 (of IntelliVent) en drukken na repositionering.",
    category: "kliniek",
    difficulty: 3,
  },
  {
    questionText: "Na behandelde pneumothorax met drain: wanneer kan iASV weer worden overwogen?",
    optionA: "Als lek is opgelost en volumemeting betrouwbaar is",
    optionB: "Direct bij plaatsen drain, zonder evaluatie",
    optionC: "Nooit meer na pneumothorax",
    optionD: "Alleen bij FiO2 100%",
    correctOption: "A",
    explanation:
      "iASV is gecontra-indiceerd bij groot lek. Na adequate behandeling en stabiel circuit kan iASV opnieuw worden overwogen.",
    category: "contra-indicaties",
    difficulty: 2,
  },
  {
    questionText: "Cuff lek test vóór extubatie: relatie met iASV?",
    optionA: "Beoordeelt lek rond cuff; groot lek is contra-indicatie voor iASV",
    optionB: "Vervangt SBT",
    optionC: "Meet IBW",
    optionD: "Stelt Pasv limit in",
    correctOption: "A",
    explanation:
      "Significant cufflekkage maakt volumemeting onbetrouwbaar. Los lek op of kies andere mode voordat je op iASV vertrouwt.",
    category: "contra-indicaties",
    difficulty: 2,
  },
  {
    questionText: "Wat is het verschil tussen peak en plateau druk?",
    optionA: "Peak inclusief weerstand; plateau zonder flow (alveolaire druk)",
    optionB: "Peak is altijd lager dan plateau",
    optionC: "Plateau meet FiO2",
    optionD: "Geen verschil",
    correctOption: "A",
    explanation:
      "Peak pressure = resistive + elastic component. Plateau (pauze) benadert alveolaire druk. Beide monitoren bij iASV-patienten.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Welke alarmen blijven cruciaal bij iASV?",
    optionA: "Druk-, volume-, apneu- en desaturatie-alarmen",
    optionB: "Geen alarmen nodig",
    optionC: "Alleen batterijalarm",
    optionD: "Alleen humidifier-alarm",
    correctOption: "A",
    explanation:
      "iASV automatiseert instellingen, maar alarms op druk, volume, apneu en SpO2 blijven essentieel voor veiligheid.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Apneu-alarm bij iASV: wat betekent dit klinisch?",
    optionA: "Geen detecteerbare patient- of ventilatorademhaling binnen drempel; onderzoek oorzaak",
    optionB: "Patient ademt te goed",
    optionC: "iASV heeft % MinVol bereikt",
    optionD: "PEEP is te laag door design",
    correctOption: "A",
    explanation:
      "Apneu-alarm vereist directe check: disconnect, sedatie, hypopneu, circuitprobleem. iASV levert mandatory breaths bij apneu.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Circuit disconnect tijdens iASV: eerste actie?",
    optionA: "Patient en circuit veiligstellen; ventilator alarm opvolgen",
    optionB: "Pasv limit verhogen",
    optionC: "% MinVol op 200%",
    optionD: "Ventilator uitschakelen zonder patientbeoordeling",
    correctOption: "A",
    explanation:
      "Disconnect is noodsituatie. Herstel circuit of handmatige beademing; iASV vereist intact circuit met betrouwbare flowmeting.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Waarom documenteer je % MinVol, PEEP, Pasv limit en FiO2 bij iASV?",
    optionA: "Voor continuïteit van zorg en evaluatie van weaning/escalatie",
    optionB: "Alleen voor facturatie",
    optionC: "Documentatie is optioneel bij closed-loop",
    optionD: "Alleen RR/TV documenteren (die stel je in)",
    correctOption: "A",
    explanation:
      "Gebruiker stuurt % MinVol, PEEP, Pasv limit en FiO2 (tenzij IntelliVent). RR/TV zijn automatisch maar moeten wel gemonitord worden.",
    category: "kliniek",
    difficulty: 1,
  },
  {
    questionText: "Guillain-Barré patient in weaningfase op iASV: aandachtspunt?",
    optionA: "Zwakke inspiratoire spieren; monitor vitale capaciteit en weaningparameters",
    optionB: "Geen weaning mogelijk",
    optionC: "iASV is contraindicated bij alle neuropathie",
    optionD: "Altijd % MinVol 200%",
    correctOption: "A",
    explanation:
      "Neuromusculaire zwakte vereist zorgvuldig weaning. iASV kan ondersteunen, maar monitor respiratoire spierkracht en CO2.",
    category: "weaning",
    difficulty: 3,
  },
  {
    questionText: "Wat is de rol van sedatie tijdens iASV-weaning?",
    optionA: "Licht sedatie kan spontane ademhaling bevorderen; diep sedatie hindert weaning",
    optionB: "Diepe sedatie is verplicht",
    optionC: "Sedatie heeft geen invloed",
    optionD: "Sedatie vervangt % MinVol",
    correctOption: "A",
    explanation:
      "Weaning vraagt balance: voldoende comfort zonder onderdrukken van spontane ademhaling. Pas sedatie en % MinVol parallel aan.",
    category: "weaning",
    difficulty: 2,
  },
  {
    questionText: "EtCO2 vs PaCO2: waarom kan gradient toenemen bij iASV?",
    optionA: "Dead space, perfusie en longpathologie beinvloeden gradient; niet alleen % MinVol",
    optionB: "EtCO2 is altijd gelijk aan PaCO2",
    optionC: "iASV meet PaCO2 direct",
    optionD: "Gradient betekent sensor defect",
    correctOption: "A",
    explanation:
      "EtCO2 volgt PaCO2 maar gradient varieert (shunt, dead space, hemodynamie). Gebruik ABG bij twijfel over ventilatie adequaatheid.",
    category: "kliniek",
    difficulty: 2,
  },
  {
    questionText: "Patient IBW 50 kg, % MinVol 120%. Minuutvolume?",
    optionA: "6 L/min",
    optionB: "5 L/min",
    optionC: "12 L/min",
    optionD: "3 L/min",
    correctOption: "A",
    explanation: "100% = 50 × 0,1 = 5 L/min. 120% = 5 × 1,2 = 6 L/min.",
    category: "instellingen",
    difficulty: 2,
  },
  {
    questionText: "Kind IBW 20 kg: welke L/kg waarde geldt ongeveer voor minuutvolume?",
    optionA: "Tussen 0,3 (3 kg) en 0,1 (30 kg) L/kg — bij 20 kg dichter bij 0,1 L/kg",
    optionB: "Altijd 0,5 L/kg",
    optionC: "0,1 L/kg geldt pas vanaf 100 kg",
    optionD: "Pediatrisch minuutvolume is niet instelbaar",
    correctOption: "A",
    explanation:
      "Pediatrische schaal: 0,3 L/kg bij 3 kg tot 0,1 L/kg bij 30 kg. Bij 20 kg zit je in het onderste deel van het pediatrische bereik.",
    category: "instellingen",
    difficulty: 3,
  },
  {
    questionText: "Wat is reverse triggering?",
    optionA: "Ventilator-initiated breath triggert patientinspanning (diaphragma)",
    optionB: "Patient triggert ventilator twee keer",
    optionC: "PEEP daalt bij inspiratie",
    optionD: "Expiratie wordt verlengd door FiO2",
    correctOption: "A",
    explanation:
      "Reverse triggering is een vorm van asynchronie waarbij mandatory breaths patienteffort uitlokken. Herkenbaar op ventilatorgrafieken.",
    category: "kliniek",
    difficulty: 3,
  },
  {
    questionText: "Waarom is proximale sensor plaatsing vlak bij Y-stuk essentieel?",
    optionA: "Meet patient-side flow/volume; minder beïnvloed door compressible volume in circuit",
    optionB: "Alleen esthetisch",
    optionC: "Vervangt bloedgasanalyse",
    optionD: "Meet cuffdruk",
    correctOption: "A",
    explanation:
      "Sensor dicht bij patient geeft nauwkeurigere TV/flow voor iASV closed-loop sturing, vooral bij compliance van het circuit.",
    category: "techniek",
    difficulty: 2,
  },
  {
    questionText: "iASV vs handmatige PCV: belangrijkste verschil?",
    optionA: "iASV past RR, TV en Ti breath-by-breath automatisch aan",
    optionB: "PCV past automatisch FiO2 aan",
    optionC: "iASV heeft geen druklimiet",
    optionD: "PCV gebruikt geen PEEP",
    correctOption: "A",
    explanation:
      "Handmatige PCV heeft vaste RR/TV (of druk). iASV optimaliseert patroon continu binnen % MinVol en Pasv limit.",
    category: "basis",
    difficulty: 1,
  },
  {
    questionText: "Welke parameter helpt mechanische belasting van de longen te schatten?",
    optionA: "Mechanical power (geïntegreerd uit druk, volume, flow)",
    optionB: "Alleen hartfrequentie",
    optionC: "Cuffdruk",
    optionD: "Kamer temperatuur",
    correctOption: "A",
    explanation:
      "Mechanical power combineert druk- en volumeparameters. iASV 1.1 streeft naar lagere mechanical power via RR/TV-optimalisatie.",
    category: "techniek",
    difficulty: 3,
  },
  {
    questionText: "Intra-abdominale hypertensie: aandacht bij iASV?",
    optionA: "Verlaagde compliance/hoogte diafragma; monitor drukken en oxygenatie",
    optionB: "Geen invloed op ventilatie",
    optionC: "iASV contraindicated altijd",
    optionD: "Alleen Pasv limit verlagen naar 0",
    correctOption: "A",
    explanation:
      "IAH beinvloedt compliance en plateau druk. iASV past RR/TV aan, maar monitor drukken, CO2 en hemodynamiek.",
    category: "kliniek",
    difficulty: 3,
  },
  {
    questionText: "Waarom is training in ventilatorgrafieken belangrijk bij iASV?",
    optionA: "Asynchronie en AutoPEEP zijn visueel herkenbaar op flow- en drukcurves",
    optionB: "Grafieken zijn alleen voor servicetechnici",
    optionC: "iASV toont geen curves",
    optionD: "Curves vervangen klinische beoordeling volledig",
    correctOption: "A",
    explanation:
      "Ondanks automatisering helpen flow-, druk- en volumecurves bij het herkennen van double triggering, ineffective efforts en AutoPEEP.",
    category: "kliniek",
    difficulty: 1,
  },
];
